spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        service-name: consumer-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.consumer.entity.AuditPayload
        spring.json.use.type.headers: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200

rabbitmq:
  queue: patient-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always